# Generated by Django 4.2.1 on 2024-03-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trb', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
